### ISSUE TITLE
I'm getting Invalid login or password? but, I put my right credentials.. What is the reason?

### ISSUE THREAD

**Issue by ahmadbintariq4u** [SeunMatt/mysql-backup4j#17]
![image](https://user-images.githubusercontent.com/75003816/124122126-2cb26780-da8f-11eb-88d1-9a5fa0e5485f.png)

Stack Trace:

javax.mail.AuthenticationFailedException: 535 5.7.0 Invalid login or password

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:648)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:583)
	at javax.mail.Service.connect(Service.java:313)
	at javax.mail.Service.connect(Service.java:172)
	at javax.mail.Service.connect(Service.java:121)
	at javax.mail.Transport.send0(Transport.java:190)
	at javax.mail.Transport.send(Transport.java:120)
	at com.smattme.EmailService.sendMail(EmailService.java:149)

**Comment by ahmadbintariq4u** [comment]
My Mistake
