### ISSUE TITLE
javax.mail.MessagingException: Could not convert socket to TLS;

### ISSUE THREAD

**Issue by ahmadbintariq4u** [SeunMatt/mysql-backup4j#18]
![image](https://user-images.githubusercontent.com/75003816/124222885-0a1a6000-db1c-11eb-9ecb-948ec545b2b7.png)

javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1652)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:534)
	at javax.mail.Service.connect(Service.java:313)
	at javax.mail.Service.connect(Service.java:172)
	at javax.mail.Service.connect(Service.java:121)
	at javax.mail.Transport.send0(Transport.java:190)
	at javax.mail.Transport.send(Transport.java:120)
	at com.smattme.EmailService.sendMail(EmailService.java:149)
	at com.smattme.MysqlExportService.export(MysqlExportService.java:298)
	at com.atcollection.dashboard.setting.Setting.lambda$emailBackup$0(Setting.java:205)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)

**Comment by SeunMatt** [comment]
Hello @ahmadbintariq4u 

This exception has to do with Java mail not able to communicate with Mailtrap. You should check your Mailtrap config, the email port is usually `2525` and the username and password are usually alphanumeric and not your Gmail account

**Comment by ahmadbintariq4u** [comment]
@SeunMatt  Thanks bro. 
one more thing.. Is the EMAIL_FROM && EMAIL_TO is the gmails?

**Comment by SeunMatt** [comment]
The `EMAIL_TO` is the email where the zipped backup files will be sent, it can be any valid email - Gmail or others.
The `EMAIL_FROM` can also be any valid email address.

**Comment by SeunMatt** [comment]
cc @ahmadbintariq4u
